import { Assignment, QuestionPaper, QuestionDifficulty, Question } from '@/types';
import { format } from 'date-fns';

interface Props {
  assignment: Assignment;
  questionPaper: QuestionPaper;
}

function QuestionItem({ question, index }: { question: Question; index: number }) {
  return (
    <div className="py-4 border-b border-dashed border-gray-100 last:border-0 text-sm text-gray-800">
      <div className="flex items-start gap-2">
        <span className="font-bold text-gray-900 w-6 flex-shrink-0">{index}.</span>
        <div className="flex-1">
          <div className="leading-relaxed">
            <span className="font-semibold text-gray-500 mr-2">({question.difficulty})</span>
            <span className="text-gray-900 font-medium">{question.text}</span>
            <span className="font-semibold text-gray-500 ml-2">[{question.marks} Mark{question.marks !== 1 ? 's' : ''}]</span>
          </div>

          {/* MCQ Options */}
          {question.options && question.options.length > 0 && (
            <div className="mt-3 grid grid-cols-2 gap-x-6 gap-y-2 pl-2">
              {question.options.map((opt, oi) => (
                <div key={oi} className="flex items-start gap-1.5 text-gray-700">
                  <span className="font-semibold text-gray-900 flex-shrink-0">
                    {String.fromCharCode(65 + oi)})
                  </span>
                  <span>{opt}</span>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

export default function QuestionPaperView({ assignment, questionPaper }: Props) {
  const totalMarks = assignment.numQuestions * assignment.marksPerQuestion;
  let qCounter = 0;

  return (
    <div
      id="question-paper"
      className="bg-white border border-gray-200 overflow-hidden max-w-4xl mx-auto print-paper shadow-md rounded-[16px] p-8 space-y-6"
    >
      {/* Exam Header */}
      <div className="text-center py-4 border-b border-gray-200">
        <h1 className="text-xl font-bold text-gray-900 tracking-tight uppercase">Delhi Public School, Sector-4, Bokaro</h1>
        <h2 className="text-md font-semibold text-gray-700 mt-1">Subject: Science</h2>
        <h3 className="text-sm font-medium text-gray-600 mt-0.5">Class 5th</h3>
        
        <div className="flex items-center justify-between mt-6 text-xs text-gray-700 font-bold uppercase tracking-wide">
          <span>Time Allowed: 45 Minutes</span>
          <span>Maximum Marks: {totalMarks}</span>
        </div>
      </div>

      {/* Student Info Section */}
      <div className="py-2 border-b border-gray-200 flex flex-wrap gap-x-6 gap-y-4 text-xs font-semibold text-gray-700">
        <div className="flex-1 min-w-[200px] flex items-center gap-2">
          <span>Name:</span>
          <div className="flex-1 border-b border-dotted border-gray-400 h-4" />
        </div>
        <div className="w-[180px] flex items-center gap-2">
          <span>Roll Number:</span>
          <div className="flex-1 border-b border-dotted border-gray-400 h-4" />
        </div>
        <div className="w-[180px] flex items-center gap-2">
          <span>Class 5th Section:</span>
          <div className="flex-1 border-b border-dotted border-gray-400 h-4" />
        </div>
      </div>

      {/* General Instructions */}
      <div className="py-2 border-b border-gray-200 text-xs text-gray-700 italic font-semibold">
        Note: All questions are compulsory unless stated otherwise.
      </div>

      {/* Sections */}
      <div className="space-y-8 py-4">
        {questionPaper.sections.map((section) => (
          <div key={section.title}>
            {/* Section header */}
            <div className="text-center mb-6">
              <h3 className="font-bold text-gray-900 text-base uppercase tracking-wider">{section.title}</h3>
              <p className="text-xs text-gray-500 mt-1 italic font-semibold">{section.instruction}</p>
            </div>

            {/* Questions */}
            <div className="space-y-1">
              {section.questions.map((q) => {
                qCounter++;
                return <QuestionItem key={qCounter} question={q} index={qCounter} />;
              })}
            </div>
          </div>
        ))}
      </div>

      {/* Footer */}
      <div className="pt-6 border-t border-gray-200 text-center">
        <p className="text-xs text-[#A0AEC0] font-semibold">
          Generated by VedaAI · {format(new Date(questionPaper.generatedAt), 'MMMM d, yyyy')} ·{' '}
          <span className="text-black font-bold">End of Question Paper</span>
        </p>
      </div>
    </div>
  );
}
